version: '3.8'

services:
  # web api
  webapi:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Database=Server=sqlserver;Database=challenge;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - kafka__bootstrapServer=kafka:9092
      - elasticsearch__uri=http://elasticsearch:9200
      - elasticsearch__defaultIndex=permissions
      - elasticsearch__username=elastic
      - elasticsearch__password=12345678 
    depends_on:
      - sqlserver
      - kafka
      - elasticsearch
  
  # configuracion zookeper para kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"

  # base de datos
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"

  # elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.license.self_generated.type=trial"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=12345678"
    ports:
      - "9200:9200"
